# https://akrabat.com/using-github-actions-to-add-go-binaries-to-a-release/

name: Build Release Binaries

on:
  release:
    types:
      - created

jobs:
  build:
    name: Build Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build binaries
        run: ./internal/cli/scripts/build-binaries.sh

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./cmd/cli/release/deeploy-*
          file_glob: true
